name: test-and-lint
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run:  go test -v ./... -coverprofile="coverage.out"

    - uses: codecov/codecov-action@v2
      with:
        files: coverage.out
        flags: unittests # optional
        name: go-cache
        fail_ci_if_error: true # optional (default = false)
        verbose: false # optional (default = false)

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"