# THIS FILE IS GENERATED AUTOMATICALLY BY RUNNING gen-workflow.sh
# DON'T CHANGE IT MANUALLY TO AVOID YOUR CHANGES BEING OVERWRITTEN
# USE workflow-template.yaml FOR MAKING CHANGES IN WORKFLOWS
name: build-common
on:
  push:

jobs:
  build:

    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: lint
      uses: golangci/golangci-lint-action@v2

    - name: Test
      run:  go test -v ./... -coverprofile="coverage.out"

    - uses: codecov/codecov-action@v2
      with:
        files: coverage.out
        flags: unittests # optional
        name: go-cache
        fail_ci_if_error: true # optional (default = false)
        verbose: false # optional (default = false)

